languageCode = "en-us"
title = "Geeky Ramblings"

theme = "purehugo"
Paginate = 10
disqusShortname = "h4md1"

[params]
  twitterName = "killerwolf"
  githubName = "killerwolf"
  description = "of a Web Developper"
  google_analytics = "UA-xxxxxx-xx"

[permalink]
  post = "/:year/:month/:title/"